### ISSUE TITLE
Move to CSC Tenn. Tech GitLab 

### ISSUE THREAD

**Issue by akondrahman** [Femi-Tofade/CSC-6220-Data-Mining#3]
Please!

**Comment by Femi-Tofade** [comment]
Hi Dr Rahman..
Can you please provide the link to the CSC Gitlab? As i have no idea where to find it (I am not a CSC grad student)

I am trying to create a gitlab for the team on the school's Gitlab

**Comment by akondrahman** [comment]
https://gitlab.csc.tntech.edu/
